import_from_git(url: 'https://github.com/marcelo-schroeder/IFAFastfile.git')

platform :ios do

  desc "Release new version of open source framework"
  desc "Optional parameter: versionNumber (if not provided, patch version number is incremented by 1)"
  lane :releaseFramework do |options|
    ensureGitBranch
    #updateDependencies
    #runAllTests
    updateVersionNumber(options)
    commitNewFrameworkVersionRelease
    addVersionGitTag
    pushToGitRemote
    gitMergeIntoRemoteMasterBranch
    #pod_push
  end

  private_lane :commitNewFrameworkVersionRelease do
    sh "git add -A && git commit -m 'New version release'"
  end

  private_lane :gitMergeIntoRemoteMasterBranch do
    sh "git checkout master && git pull origin master && git merge #{ENV['IFA_GIT_BRANCH']} && git push origin master && git checkout #{ENV['IFA_GIT_BRANCH']}"
  end

end